# Generated by Django 5.2.8 on 2025-11-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(
                        help_text="Une brève description de la fiche",
                        verbose_name="Description",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Le résumé complet du cours", verbose_name="Contenu"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Mathématiques, Physique, Histoire...",
                        max_length=100,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Débutant"),
                            ("intermediate", "Intermédiaire"),
                            ("advanced", "Avancé"),
                        ],
                        default="intermediate",
                        max_length=20,
                        verbose_name="Niveau de difficulté",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche",
                "verbose_name_plural": "Fiches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="fiches_fich_created_dcb33d_idx"
                    ),
                    models.Index(
                        fields=["category"], name="fiches_fich_categor_75e986_idx"
                    ),
                ],
            },
        ),
    ]
